import { useState } from "react";
import { ArrowUpRight, ArrowRight, Check, FileText, PencilLine, Play, Sparkles, X } from "lucide-react";
import * as Dialog from "@radix-ui/react-dialog";

const walkthrough = [
  ["A simple introduction", "Start with your name, contact details, and a little about what you do."],
  ["Experience that speaks", "Add your strengths and the work you're proud of. Every journey counts."],
  ["Ready for your next chapter", "Add your photo and save. Your personal career space is ready to explore."],
];

export default function CandidateWelcome({ onUpload, onCreate }) {
  const [demo, setDemo] = useState(false);
  const [slide, setSlide] = useState(0);
  return <section className="text-[#24222b]">
    <div className="pt-[38px] pb-7 text-center sm:pt-[58px] sm:pb-[35px] min-[1500px]:pt-[75px] [&_h1]:relative [&_h1]:mx-auto [&_h1]:mt-[22px] [&_h1]:mb-[19px] [&_h1]:w-fit [&_h1]:text-[clamp(42px,5.4vw,70px)] [&_h1]:leading-[1.08] [&_h1]:tracking-[-2px] sm:[&_h1]:tracking-[-3.8px] [&_h1]:font-[520] [&>p]:text-xs sm:[&>p]:text-sm [&>p]:leading-[1.8] [&>p]:text-[#85808c]">
      <span className="inline-flex items-center gap-2 text-[8px] font-[650] tracking-[1.4px] text-[#777080] sm:text-[10px] sm:tracking-[2px] [&>span]:size-1.5 [&>span]:rounded-full [&>span]:bg-[#8b6aca] [&>span]:shadow-[0_0_0_4px_#ece7f4]"><span /> A FRESH START, BUILT AROUND YOU</span>
      <h1>Your next chapter<br />starts <span className="font-[Georgia,serif] font-normal italic text-[#8463b3]">with you.</span><Sparkles className="absolute -right-12 top-3 hidden text-[#aa92cf] sm:block" size={34} strokeWidth={1.3} /></h1>
      <p>You bring the ambition. We'll help you tell your story.<br className="hidden sm:block" /> Let's create a profile that feels like you.</p>
    </div>
    <div className="mx-auto grid max-w-[850px] grid-cols-1 gap-4 sm:grid-cols-2 sm:gap-[22px] min-[1500px]:max-w-[930px]">
      <button className="relative min-w-0 cursor-pointer overflow-hidden rounded-[22px] border p-[23px] text-left text-inherit transition-[transform,box-shadow] duration-200 hover:-translate-y-1 hover:shadow-[0_18px_40px_#34264d0d] focus-visible:outline-3 focus-visible:outline-offset-4 focus-visible:outline-[#a58bc8] motion-reduce:transition-none motion-reduce:hover:transform-none sm:px-[30px] sm:pt-[25px] min-[1500px]:px-9 min-[1500px]:py-[30px] [&_h2]:mt-2 [&_h2]:mb-3 [&_h2]:text-[25px] [&_h2]:font-[550] [&_h2]:leading-[1.25] [&_h2]:tracking-[-0.8px] [&>p]:text-xs [&>p]:leading-[1.8] border-[#e4dfec] bg-linear-135 from-[#f4effc] to-[#ece5f7] [&>p]:text-[#82778f]" onClick={onUpload}>
        <div className="flex items-center justify-between"><span className="grid size-[43px] place-content-center rounded-[13px] bg-white/60 text-[#775aab]"><FileText size={23} strokeWidth={1.6} /></span><span className="text-[8px] font-[650] tracking-[1.2px] text-[#8d7ba6]">QUICK START</span></div>
        <div className="relative my-3 flex h-[120px] items-center justify-center sm:mb-[17px] sm:h-[145px] min-[1500px]:h-[165px]" aria-hidden="true"><div className="h-[110px] w-[125px] -rotate-7 rounded-[7px] border border-[#e8dff3] bg-[#fffdfd] p-[15px] shadow-[0_9px_16px_#5645720b] sm:h-[130px] [&_i]:mb-1.5 [&_i]:block [&_i]:h-1 [&_i]:rounded [&_i]:bg-[#eae5ef] [&>i:nth-of-type(2)]:w-4/5"><span className="float-left size-[21px] rounded-full bg-[#dfd4ef]" /><div className="mt-1 mb-[13px] ml-7 [&>i:first-child]:w-[42px] [&>i:first-child]:bg-[#b6a2d3]"><i /><i /></div><div className="mb-3 h-px bg-[#efeaf4]" /><i /><i /><i /><div className="mt-[13px] flex gap-1 [&>b]:h-2.5 [&>b]:w-[22px] [&>b]:rounded-[3px] [&>b]:bg-[#efe7fa]"><b /><b /><b /></div></div><span className="absolute bottom-[15px] left-1/2 flex -translate-x-[24%] rotate-3 items-center gap-1.5 whitespace-nowrap rounded-[7px] border border-[#e5dded] bg-white px-2.5 py-2 text-[9px] text-[#8b70ad] shadow-[0_4px_15px_#7055840a]"><Check size={14} /> Your experience, organised</span></div>
        <h2>Have a resume?<br />Give it a new beginning.</h2>
        <p>Upload your resume. We'll fill in the details,<br className="hidden sm:block" /> then you can make them your own.</p>
        <span className="mt-[23px] flex items-center justify-between gap-5 rounded-[10px] bg-[#8060ad] px-[17px] py-3.5 text-xs font-[550] text-white">Upload your resume <ArrowUpRight size={20} /></span>
        <span className="mt-3 block text-center text-[9px] text-[#9b8fab]">PDF, DOC or DOCX · up to 10 MB</span>
      </button>
      <button className="relative min-w-0 cursor-pointer overflow-hidden rounded-[22px] border p-[23px] text-left text-inherit transition-[transform,box-shadow] duration-200 hover:-translate-y-1 hover:shadow-[0_18px_40px_#34264d0d] focus-visible:outline-3 focus-visible:outline-offset-4 focus-visible:outline-[#a58bc8] motion-reduce:transition-none motion-reduce:hover:transform-none sm:px-[30px] sm:pt-[25px] min-[1500px]:px-9 min-[1500px]:py-[30px] [&_h2]:mt-2 [&_h2]:mb-3 [&_h2]:text-[25px] [&_h2]:font-[550] [&_h2]:leading-[1.25] [&_h2]:tracking-[-0.8px] [&>p]:text-xs [&>p]:leading-[1.8] border-[#e7e3da] bg-[#fffefa] [&>p]:text-[#8b8378]" onClick={onCreate}>
        <div className="flex items-center justify-between"><span className="grid size-[43px] place-content-center rounded-[13px] bg-[#f1ede5] text-[#81745e]"><PencilLine size={23} strokeWidth={1.6} /></span><span className="text-[8px] font-[650] tracking-[1.2px] text-[#918575]">YOUR STORY, YOUR WAY</span></div>
        <div className="relative my-3 flex h-[120px] -rotate-3 flex-col items-center justify-center gap-[9px] px-4 py-3 sm:mb-[17px] sm:h-[145px] min-[1500px]:h-[165px]" aria-hidden="true"><div className="flex w-full items-center gap-3 rounded-[7px] border border-[#eae6df] bg-white px-[13px] py-[11px] text-[10px] text-[#83776b] shadow-[0_3px_6px_#483b2903] last:translate-x-[11px] [&>span:first-child]:text-[8px] [&>span:first-child]:text-[#b4a48d] [&>svg]:ml-auto [&>svg]:text-[#b2a088]"><span>01</span> A little about you <Check size={14} /></div><div className="flex w-full items-center gap-3 rounded-[7px] border border-[#eae6df] bg-white px-[13px] py-[11px] text-[10px] text-[#83776b] shadow-[0_3px_6px_#483b2903] last:translate-x-[11px] [&>span:first-child]:text-[8px] [&>span:first-child]:text-[#b4a48d] [&>svg]:ml-auto [&>svg]:text-[#b2a088]"><span>02</span> What you're great at <Check size={14} /></div><div className="flex w-full items-center gap-3 rounded-[7px] border border-[#eae6df] bg-white px-[13px] py-[11px] text-[10px] text-[#83776b] shadow-[0_3px_6px_#483b2903] last:translate-x-[11px] [&>span:first-child]:text-[8px] [&>span:first-child]:text-[#b4a48d] [&>svg]:ml-auto [&>svg]:text-[#b2a088]"><span>03</span> Where you've been <span className="ml-auto h-3 w-px bg-[#9d83bc]" /></div></div>
        <h2>A blank page.<br />Endless possibilities.</h2>
        <p>Build your profile one simple step at a time.<br className="hidden sm:block" /> No resume? You're in the right place.</p>
        <span className="mt-[23px] flex items-center justify-between gap-5 rounded-[10px] bg-[#29262e] px-[17px] py-3.5 text-xs font-[550] text-white">Create your resume <ArrowUpRight size={20} /></span>
        <span className="mt-3 block text-center text-[9px] text-[#a2998c]">Personal details · Skills · Experience · Photo</span>
      </button>
    </div>
    <div className="mt-[30px] flex flex-wrap items-center justify-center gap-3 text-[11px] text-[#968c99] sm:text-xs [&>button]:flex [&>button]:cursor-pointer [&>button]:items-center [&>button]:gap-2 [&>button]:bg-transparent [&>button]:font-[550] [&>button]:text-[#51425f]"><span>Want to look around first?</span><button onClick={() => setDemo(true)}><span className="grid size-[25px] place-content-center rounded-full border border-[#ddd5e7]"><Play size={11} fill="currentColor" /></span> Get a demo <ArrowRight size={15} /></button></div>
    <p className="mt-[27px] text-center font-[Georgia,serif] text-xs italic text-[#ada3ad] sm:mt-10">Your journey is unique. Your profile should be, too.</p>
    <Dialog.Root open={demo} onOpenChange={setDemo}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-100 grid place-items-center bg-[#25202b]/40 p-6 backdrop-blur-[6px]"><Dialog.Content aria-describedby={undefined} className="relative w-full max-w-[510px] rounded-3xl bg-[#faf9f6] px-6 py-8 sm:p-10 [&_h2]:my-3 [&_h2]:text-[25px] [&_h2]:tracking-[-0.8px] [&>p:last-of-type]:text-sm [&>p:last-of-type]:leading-[1.8] [&>p:last-of-type]:text-[#89818d] [&_button]:cursor-pointer [&_button:disabled]:cursor-default">
      <button autoFocus className="absolute top-[18px] right-[18px]" aria-label="Close demo" onClick={() => setDemo(false)}><X size={20} /></button>
      <span className="inline-flex items-center gap-2 text-[8px] font-[650] tracking-[1.4px] text-[#777080] sm:text-[10px] sm:tracking-[2px] [&>span]:size-1.5 [&>span]:rounded-full [&>span]:bg-[#8b6aca] [&>span]:shadow-[0_0_0_4px_#ece7f4]">A PREVIEW OF YOUR JOURNEY</span><div className="my-[26px] flex items-center gap-3 rounded-[14px] bg-[#f0eaf7] px-4 py-6 [&>span]:rounded-full [&>span]:bg-[#dfd0ef] [&>span]:p-3.5 [&>span]:text-[#7d5da4] [&_strong]:text-sm [&_p]:mt-[3px] [&_p]:text-[10px] [&_p]:text-[#9685a6] [&>svg]:ml-auto [&>svg]:text-[#a78cbe]"><span>AM</span><div><strong>Alex Morgan</strong><p>Product designer · Sample profile</p></div><Sparkles size={24} /></div>
      <p className="text-[10px] tracking-[2px] text-[#a28ab6]">0{slide + 1} / 03</p><Dialog.Title>{walkthrough[slide][0]}</Dialog.Title><p>{walkthrough[slide][1]}</p>
      <div className="mt-[25px] flex items-center justify-between text-[13px] [&>button:last-child]:mt-0 [&>button:disabled]:opacity-30"><button disabled={slide === 0} onClick={() => setSlide(slide - 1)}>Back</button><button className="mt-[23px] flex items-center justify-between gap-5 rounded-[10px] bg-[#8060ad] px-[17px] py-3.5 text-xs font-[550] text-white" onClick={() => slide < 2 ? setSlide(slide + 1) : onCreate()}>{slide < 2 ? "Next" : "Create my profile"}<ArrowRight size={17} /></button></div>
    </Dialog.Content></Dialog.Overlay></Dialog.Portal></Dialog.Root>
  </section>;
}
